#!/usr/bin/env bash

demo_helper_type_speed=5000

# shellcheck source=../../tools/demo-helper.sh
source "$(dirname "$0")/../../tools/demo-helper.sh"

comment "1. Set up for custom domain 'go.rytswd'"
comment_w "Get into domain server directory"
execute "cd ../simple-domain-server"
comment_w "Create certificate for local testing"
execute "mkcert go.rytswd"

comment_w "Add name resolution just for local testing"
execute "sudo vim /etc/hosts # With following entry: 127.0.0.1 go.rytswd"
comment_w "Start server in the background"
execute "PORT=443 go run main.go &"
comment_w "Test server"
execute "curl https://go.rytswd/gocon-main-demo/"
comment_w "Now we have a custom domain set up to handle Go module request."
execute "cd ../3-all-in-one"

comment "2. See what we have"
execute "cd src; tree ."
comment_w "See some key differences from the 2nd demo"
execute "cat brazil-farm/go.mod"
execute "cat uk-farm/go.mod"
comment_w "The difference in GoCon Cafe is important"
execute "cat gocon-cafe/go.mod"
comment_w "There is also a new service called GoCon Restaurant"
execute "cat gocon-restaurant/go.mod"
comment_g "Note how the commit hash is different, although they both depend on uk-farm package"
execute "git log --oneline --all --decorate --graph | head"

comment_w "Make sure all services compile correctly"
execute "cd gocon-cafe; go build"
execute "rm gocon-cafe; cd .."
execute "cd gocon-restaurant; go run main.go"
execute "cd .."

comment "3. Update a function in UK farm"
comment_w "Add a brand new function in here."
execute "cd uk-farm"
execute "vim beef/beef.go"
comment_w "Try using the newly added function in GoCon Restaurant"
execute "cd ../gocon-restaurant"
execute "vim main.go"
comment_w "Try running go run main.go - which would fail"
execute "go run main.go"
comment_w "GoCon Restaurant is referring to the version that does not have the new function"
comment_w "Let's push the UK farm update to GitHub"
execute "git add ../uk-farm/beef/beef.go; git commit -m 'Add new function to UK farm'; git push"
comment_w "Now, the new commit has been pushed to the server, so that GoCon Restaurant can find it."
execute "GOPRIVATE=go.rytswd/gocon-main-demo go get -u go.rytswd/gocon-main-demo/demos/3-all-in-one/src/uk-farm@main"
comment_w "With that, we can run 'go run main.go'"
execute "go run main.go"
